### ISSUE TITLE
Create list for all and recurse.

### ISSUE THREAD

**Issue by enpfeff** [marulango/14craft#3]
saw your post on ffxiv subreddit, kinda did somework to do this when tools werent updating as quickly as id like them to.  But the number one issue with your current implementation is that you dont recurse on the recipe outputs like the example in the comments state titanium ore is a mat that requires mats to make.  Anyways i thought i would through you my algorithm for this so you could integrate it as you see fit.

https://github.com/enpfeff/ffxiv-crafting/blob/master/server/ffxiv/ffxiv.service.js

the only bug i know about right now is the ability to determine if the craft creates multiple outputs e.g. when an alc makes a potion it creates 3 outputs not one.  Maybe this data is hidden the api calls i use.  Either way have fun!

**Comment by marulango** [comment]
Hi there!
Made a refactor some time ago and added this functionality. 
Thanks for opening the issue and sharing your code ✨
